sudo: false
language: node_js
node_js:
  - '8'
  - '6'
  - '4'
os:
  - linux
  - osx
cache:
  directories:
  - node_modules
install:
  - npm i -g npx
  - npm install
script:
  - node --version
  - npm --version
  - npx --version
  - npm test
after_test:
  - npx codecov
